export const FETCH_CATS_REQUEST = 'FETCH_CATS_REQUEST';
export const DELETE_CAT_REQUEST = 'DELETE_CAT_REQUEST';
export const DELETE_CAT_SUCCESS = 'DELETE_CAT_SUCCESS';
export const CATS_SUCCESS = 'CATS_SUCCESS';
export const CATS_FAILURE = 'CATS_FAILURE';